name: Assign new issue to project

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign-one-project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign NEW issues to Considering
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/monalisatalk-fan-site/roadmap/projects/1'
          column_name: '🤔 検討中...'

      - name: Assign issues with `bug` label to ToDo
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: contains(github.event.issue.labels.*.name, 'bug')
        with:
          project: 'https://github.com/monalisatalk-fan-site/roadmap/projects/1'
          column_name: '✅ To Do'
